[UI]
name = "AgentFlow"
description = "AI个人助理，支持真·流式响应和会话续跑"

[features]
# 启用流式响应
enable_streaming = true
# 启用telemetry用于调试（生产环境可关闭）
enable_telemetry = false

[session]
# Session超时时间（秒）
timeout = 900  # 15分钟
# 用户session超时时间（秒）
user_session_timeout = 900  # 15分钟

[websocket]
# WebSocket ping间隔（秒）
ping_interval = 30
# WebSocket ping超时时间（秒）
ping_timeout = 60
# 允许的源（生产环境设置具体域名）
allow_origins = ["*"]

[server]
# 单worker配置（本地开发推荐）
workers = 1
# 主机
host = "0.0.0.0"
# 端口
port = 8000